# Generated by Django 5.2 on 2025-05-01 12:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('amount_due_ugx', models.IntegerField(blank=True, default=0, null=True)),
                ('deposit_paid_ugx', models.IntegerField(blank=True, default=0, null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('sales_agent_name', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('due_date', models.DateField()),
                ('produce_name', models.CharField(max_length=100)),
                ('tonnage_kgs', models.IntegerField(default=0)),
                ('date_of_dispatch', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_produce', models.CharField(max_length=100)),
                ('type_of_produce', models.CharField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time_of_produce', models.TimeField()),
                ('tonnage_kg', models.IntegerField()),
                ('cost_ugx', models.IntegerField()),
                ('name_of_dealer', models.CharField()),
                ('branch_name', models.CharField()),
                ('contact_of_dealer', models.IntegerField()),
                ('selling_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_salesagent', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userprofile_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userprofile_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.IntegerField(default=0, null=True)),
                ('issued_quantity', models.IntegerField(default=0, null=True)),
                ('received_quantity', models.IntegerField(default=0, null=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('type_of_stock', models.CharField(max_length=100, null=True)),
                ('unit_price', models.IntegerField(default=0, null=True)),
                ('totalcost', models.IntegerField(default=0, null=True)),
                ('sales_agent_name', models.CharField(max_length=100)),
                ('catergory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kglapp.catergory')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage_kgs', models.IntegerField(default=0, null=True)),
                ('unit_price', models.IntegerField(default=0, null=True)),
                ('amount_paid_ugx', models.IntegerField(default=0, null=True)),
                ('amount_recieved', models.IntegerField(default=0, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default=False)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kglapp.stock')),
            ],
        ),
    ]
