# Generated by Django 5.2 on 2025-05-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_agent',
            new_name='sales_agent_id',
        ),
    ]
