# Generated by Django 5.2 on 2025-05-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_rename_sales_agent_sale_sales_agent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_agent_id',
            new_name='sales_agent_name',
        ),
    ]
