# Generated by Django 5.2 on 2025-05-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0003_rename_sales_agent_id_sale_sales_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sales_agent_name',
        ),
    ]
