# Generated by Django 5.2 on 2025-05-01 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0004_remove_sale_sales_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_agent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
