# Generated by Django 5.2 on 2025-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0005_sale_sales_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_agent_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
