# Generated by Django 5.2 on 2025-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0006_alter_sale_sales_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_agent_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
