# Generated by Django 5.2 on 2025-05-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0007_alter_sale_sales_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurement',
            old_name='branch_name',
            new_name='added_by',
        ),
    ]
