# Generated by Django 5.2 on 2025-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0008_rename_branch_name_procurement_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='branch_name',
            field=models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Maganjo', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch_name',
            field=models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Majango', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch_name',
            field=models.CharField(choices=[('Maganjo', 'Maganjo'), ('Matugga', 'Matugga')], default='Matugga', max_length=50),
        ),
    ]
