# Generated by Django 5.2 on 2025-05-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0009_procurement_branch_name_stock_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='time_of_produce',
        ),
    ]
